from pathlib import Path

CONFIG_FILE = Path("config.json")
TRANSPARENT_COLOR = "#010101"

DEFAULT_MESSAGE = "Set your task..."
DEFAULT_FONT_FAMILY = "Segoe UI"
DEFAULT_FONT_SIZE = 18
DEFAULT_TEXT_COLOR = "#f2f2f2"
DEFAULT_OUTLINE_COLOR = "#000000"
DEFAULT_TRANSPARENCY = 1.0
DEFAULT_LANGUAGE = "en"

ACTIVE_TEXT_COLOR = "#ff3b30"
PAUSE_TEXT_COLOR = "#1e90ff"
STOP_TEXT_COLOR = "#ffffff"
TIME_TEXT_COLOR = "#ffffff"

WRAP_LENGTH = 600
PADDING = 16
TIME_GAP = 8

HISTORY_FILE = Path("task_history.json")
